theme: jekyll-theme-minimal
title: Tim Gibson
description: >
  <a href="https://github.com/t-gibson"><i class="fab fa-github-square fa-2x"></i></a>
  <a href="https://au.linkedin.com/in/tim-gibson/"><i class="fab fa-linkedin fa-2x"></i></a>
google_analytics: UA-159835311-1
