remote_theme: t-gibson/texture

texture:
  title: Tim Gibson
  tagline: Machine Learning Engineer
  date_format: "%b %-d, %Y"
  style: black
  analytics_id: 'UA-159835311-1'

  social_links:
    github:  t-gibson
    kaggle: timgibson
    linkedIn: in/tim-gibson
